### ISSUE TITLE
Skill doesn't load on ovos-core 0.0.7

### ISSUE THREAD

**Issue by mikejgray** [JarbasSkills/skill-better-stop#12]
I'm working off an OVOS Manjaro image with ovos-core version 0.0.7 and this skill refuses to load, giving me the following traceback:

```log
 07:07:20.233 - skills - mycroft.skills.skill_loader:remove_submodule_refs:168 - DEBUG - Skill module: skill-ovos-stop_openvoiceos
 07:07:20.259 - skills - mycroft.skills.skill_loader:_create_skill_instance:541 - ERROR - Skill __init__ failed with super(type, obj): obj must be an instance or subtype of type
Traceback (most recent call last):
  File "/home/ovos/.local/lib/python3.10/site-packages/mycroft/skills/skill_loader.py", line 529, in _create_skill_instance
    self.instance = skill_creator()
  File "/home/ovos/.local/share/mycroft/skills/skill-ovos-stop.openvoiceos/__init__.py", line 47, in create_skill
    return StopSkill()
  File "/home/ovos/.local/lib/python3.10/site-packages/ovos_workshop/skills/fallback.py", line 64, in __new__
    return super().__new__(cls, *args, **kwargs)
TypeError: super(type, obj): obj must be an instance or subtype of type
```

**Comment by JarbasAl** [comment]
what version of ovos_workshop?

**Comment by mikejgray** [comment]
0.0.12a20

**Comment by mikejgray** [comment]
Downgrading to 0.0.11 resolved the issue

**Comment by JarbasAl** [comment]
fixed in https://github.com/OpenVoiceOS/OVOS-workshop/pull/83
